// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RegistroEstudiantes.Dominio.Entidades
{
    public partial class Materia
    {
        public Materia()
        {
            ProfesorMateria = new HashSet<ProfesorMateria>();
        }

        public Guid Id { get; set; }
        public string Nombre { get; set; }
        public DateTime FechaCreacion { get; set; }
        public bool? Estado { get; set; }

        public virtual ICollection<ProfesorMateria> ProfesorMateria { get; set; }
    }
}