// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RegistroEstudiantes.Dominio.Entidades
{
    public partial class ProfesorMateria
    {
        public Guid Id { get; set; }
        public Guid IdMateria { get; set; }
        public Guid IdProfesor { get; set; }

        public virtual Materia IdMateriaNavigation { get; set; }
        public virtual Profesor IdProfesorNavigation { get; set; }
    }
}